//=========================================================
// src/2_nec_receive_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8SB2_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

//-----------------------------------------------------------------------------
// Global CONSTANTS
//-----------------------------------------------------------------------------
#define SIGNAL_IN_ON 0U
#define SIGNAL_IN_OFF 1U
#define START_BURST_OFS 90U
#define START_SPACE_OFS 45U
#define LOGIC_ONE_OFS 22U
#define LOGIC_ZERO_OFS 11U
#define LED_ON 0U
#define LED_OFF 1U
#define VOL_PLUS_CODE 0xFFA857
#define VOL_MINUS_CODE 0xFFE01F

SI_SBIT(signal_in, P2, 3U);
SI_SBIT(LED0, P2, 0U);

const uint32_t DATA_LENGTH = 32;

//-----------------------------------------------------------------------------
// Global VARIABLES
//-----------------------------------------------------------------------------
uint32_t received_data = 0x00;
uint8_t counter = 0x00;

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

uint8_t Check_Within_Accepted_Range(uint8_t p_counter, uint8_t p_target,
                                    uint8_t p_accepted_tolerance)
{
  return ((p_counter >= (p_target - p_accepted_tolerance)) &&
      (p_counter <= (p_target + p_accepted_tolerance)) ? 1 : 0);
}

uint8_t i = 0;
uint8_t nec_remote_read()
{
  // check for START 9ms BURST
  counter = 0;
  while(SIGNAL_IN_ON && (counter <= START_BURST_OFS))
  {
      counter++;
      while(!TCON_TF0);
      TCON_TF0 = 0x00;
  }
  if(!Check_Within_Accepted_Range(counter, START_BURST_OFS, 10))
  {
      return 0;
  }

  // check for START 4.5ms SPACE
  counter = 0;
  while(SIGNAL_IN_OFF && (counter <= START_SPACE_OFS))
  {
      counter++;
      while(!TCON_TF0);
      TCON_TF0 = 0x00;
  }
  if(!Check_Within_Accepted_Range(counter, START_SPACE_OFS, 5))
  {
      return 0;
  }


  for (i = 0; i < DATA_LENGTH; ++i) {

      // check for LOGIC ONE SIGNAL
      counter = 0;
      while(SIGNAL_IN_ON && (counter <= LOGIC_ONE_OFS))
      {
          counter++;
          while(!TCON_TF0);
          TCON_TF0 = 0x00;
      }
      if(!Check_Within_Accepted_Range(counter, LOGIC_ONE_OFS, 2) && (counter != 0))
      {
          return 0;
      }
      else
      {
          received_data |= (1U << ((DATA_LENGTH-1)-i));
      }

      counter = 0;
      while(SIGNAL_IN_OFF && (counter <= LOGIC_ZERO_OFS))
      {
          counter++;
          while(!TCON_TF0);
          TCON_TF0 = 0x00;
      }
      if(!Check_Within_Accepted_Range(counter, LOGIC_ZERO_OFS, 2) && (counter != 0))
      {
          return 0;
      }
      else
      {
          received_data &= ~(1U << ((DATA_LENGTH-1)-i));
      }
  }

  return 1;
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();
  
  while (1) 
  {
    // $[Generated Run-time code]
    // [Generated Run-time code]$

      // if receive was successful
      if (nec_remote_read())
      {
          switch(received_data)
          {
            case(VOL_PLUS_CODE):
              LED0 = LED_ON;
              break;

            case(VOL_MINUS_CODE):
              LED0 = LED_OFF;
              break;

            default:
              LED0 = LED_OFF;
          }

      }

  }                             
}
